export const AUTH = {
    LOGIN: 'AUTH_LOGIN',
    LOGOUT: 'AUTH_LOGOUT'
}

export const DASHBOARD = {
    GET_DATA: 'DASHBOARD_GET_DATA',
}

export const ORGANIZATIONS = {
    GET_DATA: 'ORGANIZATIONS_GET_DATA',
    UPDATE_SEARCH_STRING: 'ORGANIZATIONS_UPDATE_SEARCH_STRING',
}

export const ORGANIZATION_DETAILS = {
    GET_DATA: 'ORGANIZATION_DETAILS_GET_DATA',
    UPDATE_MY_ORG: 'ORGANIZATION_DETAILS_UPDATE_MY_ORG',
    UPDATE_SEARCH_STRING: 'ORGANIZATION_DETAILS_UPDATE_SEARCH_STRING',
}

export const EMPLOYEES = {
    GET_DATA: 'EMPLOYEES_GET_DATA',
    ADD_EMPLOYEE: 'EMPLOYEES_ADD_EMPLOYEE',
    UPDATE_EMPLOYEE: 'EMPLOYEES_UPDATE_EMPLOYEE',
    REMOVE_EMPLOYEE: 'EMPLOYEES_REMOVE_EMPLOYEE',
    UPDATE_SEARCH_STRING: 'EMPLOYEES_UPDATE_SEARCH_STRING',
}

export const PROFILE = {
    GET_DATA: 'PROFILE_GET_DATA',
}